name: trufflehog-scan

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # daily at 4 AM

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install TruffleHog
        run: |
          VERSION=3.88.0
          curl -sSL https://github.com/trufflesecurity/trufflehog/releases/download/v${VERSION}/trufflehog_${VERSION}_linux_amd64.tar.gz -o trufflehog.tar.gz
          tar -xvzf trufflehog.tar.gz
          chmod +x trufflehog
          sudo mv trufflehog /usr/local/bin/


      - name: Run TruffleHog (scan full history, JSON output)
        run: |
          trufflehog git file://. \
            --json \
            --no-update \
            > trufflehog-report.json || true

      - name: Upload JSON report
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: trufflehog-report.json
